import { Canvas, useFrame } from "@react-three/fiber";
import { Environment, Text } from "@react-three/drei";
import { Physics, RigidBody, type RapierRigidBody } from "@react-three/rapier";
import * as THREE from "three";
import { useEffect, useRef } from "react";
import { useInput, type Input } from "./InputManager";
import { useMatch, type ActiveHumanRiderId } from "./GameState";
import { getTargetSpeed } from "./HorseControls";
import { getBallResetState, getShotImpulse, INITIAL_GOAL_STATE, transitionGoal } from "./PoloMechanics";

const FIELD_X=52, FIELD_Z=82;
export const RIDER_FIELD_BOUNDS={x:24,z:39};
export type SpawnXZ=readonly [number,number];
export const RIDER_SPAWNS={blue1:[0,18],blue2:[7,12],red1:[-7,-12],red2:[7,-23]} satisfies Record<string,SpawnXZ>;
export function spawnToVector3(spawn:SpawnXZ){const [x,z]=spawn;return new THREE.Vector3(x,0,z)}
type RiderId=keyof typeof RIDER_SPAWNS;
type DebugRider={id:RiderId;team:"blue"|"red";human:boolean;x:number;y:number;z:number};
type PoloDebug={activeHumanRiderId:ActiveHumanRiderId;cameraFollowId:ActiveHumanRiderId;riders:Record<RiderId,DebugRider>};
type DebugWindow=Window&{__POLO_B1_DEBUG__?:PoloDebug};
let activeDebug:PoloDebug|undefined;
function makeDebug():PoloDebug{return {activeHumanRiderId:"blue1",cameraFollowId:"blue1",riders:{blue1:{id:"blue1",team:"blue",human:true,x:0,y:0,z:0},blue2:{id:"blue2",team:"blue",human:false,x:0,y:0,z:0},red1:{id:"red1",team:"red",human:false,x:0,y:0,z:0},red2:{id:"red2",team:"red",human:false,x:0,y:0,z:0}}}}
function telemetry(id:RiderId,p:THREE.Vector3,human:boolean){const r=activeDebug?.riders[id];if(r){r.x=p.x;r.y=p.y;r.z=p.z;r.human=human}}
function Field(){return <group><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[FIELD_X,FIELD_Z]}/><meshStandardMaterial color="#237342" roughness={.9}/></mesh>{[-1,1].map(s=><group key={s} position={[0,0,s*FIELD_Z/2]}>{[-5,5].map(x=><mesh key={x} position={[x,2,0]}><boxGeometry args={[.28,4,.28]}/><meshStandardMaterial color="white"/></mesh>)}</group>)}</group>}
function RiderMesh({blue,active}:{blue:boolean;active:boolean}){return <group><mesh position={[0,1.1,0]}><boxGeometry args={[1.1,.7,2.2]}/><meshStandardMaterial color={blue?"#245fd1":"#c73333"}/></mesh><mesh position={[0,2,0]}><capsuleGeometry args={[.3,.7,6,10]}/><meshStandardMaterial color={blue?"#dce8ff":"#ffe1df"}/></mesh>{[-.4,.4].flatMap(x=>[-.7,.7].map(z=><mesh key={`${x}${z}`} position={[x,.35,z]}><boxGeometry args={[.13,.8,.13]}/><meshStandardMaterial color="#24170f"/></mesh>))}{active&&<Text position={[0,3.25,0]} fontSize={.55} color="yellow">ACTIVE</Text>}</group>}
function aiTarget(id:RiderId,b:{x:number;z:number}){if(id==="blue1")return new THREE.Vector3(b.x-6,0,b.z+4);if(id==="blue2")return new THREE.Vector3(b.x+6,0,b.z+4);if(id==="red1")return new THREE.Vector3(b.x,0,b.z);return new THREE.Vector3(b.x*.5,0,Math.min(30,b.z*.5-10))}
function PoloRider({id,ball,input,cameraTarget}:{id:RiderId;ball:React.RefObject<RapierRigidBody|null>;input:React.RefObject<Input>;cameraTarget:React.MutableRefObject<{position:THREE.Vector3;yaw:number}|null>}){const g=useRef<THREE.Group>(null),p=useRef(spawnToVector3(RIDER_SPAWNS[id])),yaw=useRef(Math.PI),speed=useRef(0),charge=useRef(0),wasHolding=useRef(false);const active=useMatch(s=>s.activeHumanRiderId),paused=useMatch(s=>s.paused),setMsg=useMatch(s=>s.setMessage);const blue=id==="blue1"||id==="blue2",human=blue&&active===id;useFrame((state,dt)=>{if(!g.current||paused)return;const isHuman=blue&&useMatch.getState().activeHumanRiderId===id;let direction:THREE.Vector3|undefined;if(isHuman){const i=input.current;speed.current=THREE.MathUtils.damp(speed.current,getTargetSpeed(i),5,dt);yaw.current+=i.steer*(.8+Math.max(0,1-Math.abs(speed.current)/16))*dt*(speed.current>=0?1:-1);direction=new THREE.Vector3(Math.sin(yaw.current),0,Math.cos(yaw.current));p.current.addScaledVector(direction,speed.current*dt);const holding=i.strike||i.power||i.backhand;if(holding)charge.current=Math.min(1,charge.current+dt*.8);if(!holding&&wasHolding.current&&charge.current>.1&&ball.current){const bp=ball.current.translation(),delta=new THREE.Vector3(bp.x,0,bp.z).sub(p.current);if(delta.length()<5){ball.current.applyImpulse(getShotImpulse({aimX:i.aimX,yaw:yaw.current,backhand:i.backhand,charge:charge.current,speed:speed.current}),true);setMsg(i.backhand?"BACKHAND!":"CLEAN STRIKE!")}}if(!holding)charge.current=0;wasHolding.current=holding}else{const b=ball.current?.translation();if(b){direction=aiTarget(id,b).sub(p.current);direction.y=0;if(Number.isFinite(direction.length())&&direction.length()>.3){direction.normalize();p.current.addScaledVector(direction,dt*5);yaw.current=Math.atan2(direction.x,direction.z)}}}p.current.x=THREE.MathUtils.clamp(p.current.x,-RIDER_FIELD_BOUNDS.x,RIDER_FIELD_BOUNDS.x);p.current.z=THREE.MathUtils.clamp(p.current.z,-RIDER_FIELD_BOUNDS.z,RIDER_FIELD_BOUNDS.z);g.current.position.copy(p.current);g.current.rotation.y=yaw.current;telemetry(id,g.current.position,isHuman);if(isHuman){cameraTarget.current={position:p.current,yaw:yaw.current};activeDebug&&(activeDebug.activeHumanRiderId=id as ActiveHumanRiderId,activeDebug.cameraFollowId=id as ActiveHumanRiderId);const desired=p.current.clone().add(new THREE.Vector3(-Math.sin(yaw.current)*12,7,-Math.cos(yaw.current)*12));state.camera.position.lerp(desired,1-Math.exp(-dt*4));state.camera.lookAt(p.current.x,p.current.y+1,p.current.z)}});return <group ref={g}><RiderMesh blue={blue} active={human}/></group>}
function Ball({api}:{api:React.MutableRefObject<RapierRigidBody|null>}){const key=useMatch(s=>s.resetKey);useEffect(()=>{const reset=getBallResetState();api.current?.setTranslation(reset.position,true);api.current?.setLinvel(reset.velocity,true)},[key,api]);return <RigidBody ref={api} colliders="ball" restitution={.72} friction={.55} position={[0,.65,0]}><mesh castShadow><sphereGeometry args={[.42,20,16]}/><meshStandardMaterial color="#f8f4e8"/></mesh></RigidBody>}
function Scene(){const ball=useRef<RapierRigidBody>(null),input=useInput(),cameraTarget=useRef<{position:THREE.Vector3;yaw:number}|null>(null),goalState=useRef(INITIAL_GOAL_STATE);const score=useMatch(s=>s.scoreGoal),paused=useMatch(s=>s.paused);useEffect(()=>{if(new URLSearchParams(window.location.search).get("e2e")!=="1")return;const debug=makeDebug(),win=window as DebugWindow;activeDebug=debug;win.__POLO_B1_DEBUG__=debug;return()=>{if(activeDebug===debug)activeDebug=undefined;if(win.__POLO_B1_DEBUG__===debug)delete win.__POLO_B1_DEBUG__}},[]);useFrame(()=>{const p=ball.current?.translation();if(!paused&&p){const result=transitionGoal(goalState.current,p);goalState.current=result.state;if(result.scored)score()}});return <><color attach="background" args={["#b9d5dd"]}/><fog attach="fog" args={["#b9d5dd",45,125]}/><ambientLight intensity={1.8}/><directionalLight position={[20,28,12]} intensity={2.2}/><Field/><Physics gravity={[0,-9.81,0]}><RigidBody type="fixed" colliders="cuboid" position={[0,-.25,0]}><mesh visible={false}><boxGeometry args={[FIELD_X,.5,FIELD_Z]}/></mesh></RigidBody><Ball api={ball}/></Physics>{(Object.keys(RIDER_SPAWNS) as RiderId[]).map(id=><PoloRider key={id} id={id} ball={ball} input={input} cameraTarget={cameraTarget}/>) }<Environment preset="park"/></>}
function Hud(){const s=useMatch();const mm=`${String(Math.floor(s.seconds/60)).padStart(2,"0")}:${String(s.seconds%60).padStart(2,"0")}`;return <div className="hud"><header><span>POLO CHAMPIONS</span><b>QUICK MATCH</b><button onClick={s.restart}>RESTART</button></header><div className="score"><small>YOUR GOALS</small><strong>{s.score}</strong><em>{mm}</em></div><div className="notice">{s.message}</div><footer><b>WASD</b> Ride <b>TAB</b> Switch <b>SHIFT</b> Gallop <b>X</b> Brake <b>SPACE</b> Strike <b>Q</b> Backhand</footer>{s.paused&&<div className="pause">PAUSED<br/><button onClick={s.togglePause}>RESUME</button></div>}</div>}
export function Game(){const setSec=useMatch(s=>s.setSeconds),paused=useMatch(s=>s.paused),toggle=useMatch(s=>s.togglePause),reset=useMatch(s=>s.resetBall),switchPlayer=useMatch(s=>s.switchPlayer);useEffect(()=>{const t=setInterval(()=>{if(!paused)setSec(Math.max(0,useMatch.getState().seconds-1))},1000);const p=()=>toggle(),r=()=>reset(),sw=()=>switchPlayer();window.addEventListener("polo-pause",p);window.addEventListener("polo-reset",r);window.addEventListener("polo-switch",sw);return()=>{clearInterval(t);window.removeEventListener("polo-pause",p);window.removeEventListener("polo-reset",r);window.removeEventListener("polo-switch",sw)}},[paused,setSec,toggle,reset,switchPlayer]);return <main><Canvas shadows camera={{fov:54,position:[0,8,25]}}><Scene/></Canvas><Hud/></main>}
