import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { Environment, Text } from "@react-three/drei";
import { Physics, RigidBody, type RapierRigidBody } from "@react-three/rapier";
import * as THREE from "three";
import { useEffect, useRef } from "react";
import { useInput } from "./InputManager";
import { useMatch } from "./GameState";
import { advanceHorseSpeed, advanceStamina, getArchetypeCoat, getBodyLean, getCameraOffset, getGait, getRiderPose, getSteeringRate, HORSE_COATS, type HorseArchetype } from "./HorseControls";
import { canApplyStrike, getBallResetState, getMalletAngle, getShotImpulse, getStrikePhase, INITIAL_GOAL_STATE, transitionGoal } from "./PoloMechanics";
import { create2v2, decideBot, rideOffImpulse, type Bot } from "./MatchRules";

const FIELD_X=52, FIELD_Z=82;
const ACTIVE_ARCHETYPE: HorseArchetype = "ALL_ROUNDER";
function Field(){ const lines:number[][]=[]; for(let z=-FIELD_Z/2;z<=FIELD_Z/2;z+=20)lines.push([0,z]); return <group><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[FIELD_X,FIELD_Z]}/><meshStandardMaterial color="#237342" roughness={.9}/></mesh>{lines.map(([x,z],i)=><mesh key={i} position={[x,.02,z]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[FIELD_X,.34]}/><meshBasicMaterial color="white"/></mesh>)}<mesh position={[0,.025,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[7.8,8.1,48]}/><meshBasicMaterial color="white"/></mesh>{[-1,1].map(s=><group key={s} position={[0,0,s*FIELD_Z/2]}>{[-5,5].map(x=><mesh key={x} position={[x,2,0]}><boxGeometry args={[.28,4,.28]}/><meshStandardMaterial color="white"/></mesh>)}<mesh position={[0,.8,0]}><boxGeometry args={[10,.12,.12]}/><meshStandardMaterial color="white"/></mesh></group>)}</group> }
function Horse({ball}:{ball:React.RefObject<RapierRigidBody|null>}){
 const g=useRef<THREE.Group>(null),rider=useRef<THREE.Group>(null),mallet=useRef<THREE.Mesh>(null),pos=useRef(new THREE.Vector3(0,0,18)),yaw=useRef(Math.PI),speed=useRef(0),stamina=useRef(1),charge=useRef(0),cool=useRef(0),swing=useRef(0),strikeClock=useRef(-1),contactFired=useRef(false),wasHolding=useRef(false),telemetryClock=useRef(0);const input=useInput();const paused=useMatch(s=>s.paused),setMsg=useMatch(s=>s.setMessage),setTelemetry=useMatch(s=>s.setTelemetry);
 useFrame((state,dt)=>{if(!g.current||paused)return;const i=input.current;const canGallop=i.gallop&&stamina.current>0;speed.current=advanceHorseSpeed(speed.current,{...i,gallop:canGallop},dt,ACTIVE_ARCHETYPE);const gait=getGait(speed.current);stamina.current=advanceStamina(stamina.current,gait==="GALLOP"&&canGallop,dt,ACTIVE_ARCHETYPE);yaw.current+=i.steer*getSteeringRate(speed.current,ACTIVE_ARCHETYPE)*dt*(speed.current>=0?1:-1);const forward=new THREE.Vector3(Math.sin(yaw.current),0,Math.cos(yaw.current));pos.current.addScaledVector(forward,speed.current*dt);pos.current.x=THREE.MathUtils.clamp(pos.current.x,-24,24);pos.current.z=THREE.MathUtils.clamp(pos.current.z,-39,39);g.current.position.copy(pos.current);g.current.rotation.y=yaw.current;const lean=getBodyLean(i.steer,speed.current,ACTIVE_ARCHETYPE);g.current.rotation.z=THREE.MathUtils.damp(g.current.rotation.z,lean,9,dt);const pose=getRiderPose(gait,i.steer,i.brake);if(rider.current){rider.current.rotation.x=THREE.MathUtils.damp(rider.current.rotation.x,pose.torsoPitch,10,dt);rider.current.rotation.z=THREE.MathUtils.damp(rider.current.rotation.z,pose.hipPitch,10,dt);rider.current.position.y=2.15+pose.seatHeight+Math.sin(state.clock.elapsedTime*pose.strideCadence)*.025;}const holding=i.strike||i.power||i.backhand,released=!holding&&wasHolding.current;swing.current=getMalletAngle(swing.current,holding,released,dt);if(released){strikeClock.current=0;contactFired.current=false;}else if(strikeClock.current>=0)strikeClock.current+=dt;const phase=getStrikePhase(strikeClock.current,holding);if(mallet.current)mallet.current.rotation.z=.4+swing.current+(phase==="FOLLOW_THROUGH"?.26:0);if(holding)charge.current=Math.min(1,charge.current+dt);cool.current-=dt;if(canApplyStrike(phase,contactFired.current)&&charge.current>.1&&cool.current<=0&&ball.current){contactFired.current=true;const bp=ball.current.translation(),delta=new THREE.Vector3(bp.x,0,bp.z).sub(pos.current);if(delta.length()<5){ball.current.applyImpulse(getShotImpulse({aimX:i.aimX,yaw:yaw.current,backhand:i.backhand,charge:charge.current,speed:speed.current,archetype:ACTIVE_ARCHETYPE}),true);cool.current=.38;setMsg(i.backhand?"BACKHAND!":"CLEAN STRIKE!");}}if(!holding&&phase==="READY")charge.current=0;wasHolding.current=holding;const offset=getCameraOffset(yaw.current,speed.current,i.steer),desired=pos.current.clone().add(new THREE.Vector3(offset.x,offset.y,offset.z)),look=pos.current.clone().addScaledVector(forward,offset.lookAhead);state.camera.position.lerp(desired,1-Math.exp(-dt*(5+Math.min(Math.abs(speed.current)/24,1)*2)));state.camera.lookAt(look.x,look.y+1,look.z);telemetryClock.current+=dt;if(telemetryClock.current>.08){telemetryClock.current=0;const bp=ball.current?.translation()??{x:0,z:0};setTelemetry({speed:Math.abs(speed.current),stamina:stamina.current,gait,charge:charge.current,strikePhase:phase,player:{x:pos.current.x,z:pos.current.z},ball:{x:bp.x,z:bp.z}})}});
 return <group ref={g}><mesh position={[0,1.15,0]} castShadow><boxGeometry args={[1.15,.75,2.35]}/><meshStandardMaterial color={HORSE_COATS[getArchetypeCoat(ACTIVE_ARCHETYPE)]}/></mesh><mesh position={[0,1.45,1.25]} rotation={[speed.current>0?-.1:0,0,0]}><boxGeometry args={[.65,.65,.9]}/><meshStandardMaterial color={HORSE_COATS[getArchetypeCoat(ACTIVE_ARCHETYPE)]}/></mesh>{[-.42,.42].flatMap(x=>[-.75,.75].map(z=><mesh key={`${x}${z}`} position={[x,.48,z]}><boxGeometry args={[.16,1,.16]}/><meshStandardMaterial color="#312018"/></mesh>))}<mesh position={[0,1.58,-.08]}><boxGeometry args={[.9,.12,1.2]}/><meshStandardMaterial color="#3D2314"/></mesh><group ref={rider}><mesh position={[0,0,-.1]}><capsuleGeometry args={[.32,.65,6,10]}/><meshStandardMaterial color="#0F2537"/></mesh><Text position={[0,.05,-.34]} rotation={[0,Math.PI,0]} fontSize={.32} color="#f8f2e3">3</Text><mesh position={[0,.55,-.1]}><sphereGeometry args={[.28,14,10]}/><meshStandardMaterial color="#f7f5ef"/></mesh></group><mesh ref={mallet} position={[.48,2,.65]} rotation={[0,0,.4]}><cylinderGeometry args={[.035,.035,2.5,8]}/><meshStandardMaterial color="#d5b66c"/></mesh></group>}
function TeamMarker({red=false}:{red?:boolean}){const jersey=red?"#8B1E1E":"#0F2537",helmet=red?"#8B1E1E":"#f7f5ef";return <group><mesh position={[0,1.15,0]}><boxGeometry args={[1.1,.7,2.25]}/><meshStandardMaterial color={red?"#b9b5aa":"#6c4327"}/></mesh><mesh position={[0,1.5,-.1]}><boxGeometry args={[.9,.08,1.2]}/><meshStandardMaterial color="#3D2314"/></mesh><mesh position={[0,1.45,-.1]}><boxGeometry args={[1,.04,1.3]}/><meshStandardMaterial color="#C99A45"/></mesh><mesh position={[0,2.15,-.1]}><capsuleGeometry args={[.32,.65,6,10]}/><meshStandardMaterial color={jersey}/></mesh><Text position={[0,2.18,-.44]} rotation={[0,Math.PI,0]} fontSize={.32} color="#f8f2e3" anchorX="center" anchorY="middle">{red?2:3}</Text><mesh position={[0,2.7,-.1]}><sphereGeometry args={[.28,14,10]}/><meshStandardMaterial color={helmet}/></mesh><mesh position={[0,2.92,-.1]}><sphereGeometry args={[.3,14,8,0,Math.PI*2,0,Math.PI/2]}/><meshStandardMaterial color={helmet}/></mesh></group>}
function Ball({api}:{api:React.MutableRefObject<RapierRigidBody|null>}){const key=useMatch(s=>s.resetKey);useEffect(()=>{const reset=getBallResetState();api.current?.setTranslation(reset.position,true);api.current?.setLinvel(reset.velocity,true)},[key,api]);return <RigidBody ref={api} colliders="ball" restitution={.72} friction={.55} position={[0,.65,0]}><mesh castShadow><sphereGeometry args={[.42,20,16]}/><meshStandardMaterial color="#f8f4e8" roughness={.45}/></mesh></RigidBody>}
function Bots({ball}:{ball:React.RefObject<RapierRigidBody|null>}){const bots=useRef<Bot[]>(create2v2().filter(b=>b.id!=="blue-1"));const groups=useRef<(THREE.Group|null)[]>([]);useFrame((_,dt)=>{const bp=ball.current?.translation()??{x:0,z:0};bots.current.forEach((bot,i)=>{const state=decideBot(bot,{x:bp.x,z:bp.z});const dx=bp.x-bot.position.x,dz=bp.z-bot.position.z,l=Math.hypot(dx,dz)||1;const rate=state==="ZONE_DEFEND"?2.2:4;bot.position.x+=dx/l*rate*dt;bot.position.z+=dz/l*rate*dt;const g=groups.current[i];if(g){g.position.set(bot.position.x,0,bot.position.z);g.rotation.y=Math.atan2(dx,dz)}});for(let i=0;i<bots.current.length;i++)for(let j=i+1;j<bots.current.length;j++){const a=bots.current[i],b=bots.current[j],dx=a.position.x-b.position.x,dz=a.position.z-b.position.z,l=Math.hypot(dx,dz);if(l>0&&l<1.5){const impulse=rideOffImpulse(a,b);a.position.x+=dx/l*impulse*dt;b.position.x-=dx/l*impulse*dt}}});return <>{bots.current.map((bot,i)=><group key={bot.id} ref={el=>{groups.current[i]=el}} position={[bot.position.x,0,bot.position.z]}><TeamMarker red={bot.team==="RED"}/></group>)}</>}
function Scene(){const ball=useRef<RapierRigidBody>(null);const score=useMatch(s=>s.scoreGoal),paused=useMatch(s=>s.paused),goalState=useRef(INITIAL_GOAL_STATE);useFrame(()=>{const p=ball.current?.translation();if(!paused&&p){const result=transitionGoal(goalState.current,p);goalState.current=result.state;if(result.scored)score()}});return <><color attach="background" args={["#b9d5dd"]}/><fog attach="fog" args={["#b9d5dd",45,125]}/><ambientLight intensity={1.8}/><directionalLight position={[20,28,12]} intensity={2.2} castShadow/><Field/><Physics gravity={[0,-9.81,0]}><RigidBody type="fixed" colliders="cuboid" position={[0,-.25,0]}><mesh visible={false}><boxGeometry args={[FIELD_X, .5, FIELD_Z]}/></mesh></RigidBody><Ball api={ball}/></Physics><Horse ball={ball}/><Bots ball={ball}/><Environment preset="park" /></>}
function Hud(){const s=useMatch(),t=s.telemetry;const mm=`${String(Math.floor(s.seconds/60)).padStart(2,"0")}:${String(s.seconds%60).padStart(2,"0")}`,radar=(v:{x:number;z:number})=>({left:`${50+v.x/FIELD_X*90}%`,top:`${50-v.z/FIELD_Z*90}%`});return <div className="hud"><header className="broadcast"><div className="team blue"><b>BLUE</b><small>YOUR GOALS</small><strong>{s.score}</strong></div><div className="match"><small>CHUKKER 1</small><strong>{mm}</strong><em>POLO CHAMPIONS</em></div><div className="team red"><strong>0</strong><b>RED</b></div><button onClick={s.restart}>RESTART</button></header><div className="archetype">{ACTIVE_ARCHETYPE.replace("_"," ")} · {t.gait}</div><div className="notice">{s.message}</div><section className="radar" aria-label="Field radar"><b>FIELD RADAR</b><i className="pip player" style={radar(t.player)}/><i className="pip ball" style={radar(t.ball)}/><i className="pip opponent" style={radar({x:9,z:-12})}/></section><section className="telemetry" aria-label="Speed and stamina"><div className="speed"><strong>{Math.round(t.speed*3.6)}</strong><small>KM/H</small></div><b>{t.gait}</b><label>STAMINA <span><i style={{width:`${t.stamina*100}%`}}/></span></label></section>{t.strikePhase==="WIND_UP"&&<section className="swing" aria-label="Swing charge">SWING POWER <span><i style={{width:`${t.charge*100}%`}}/></span></section>}<footer><b>WASD</b> Ride <b>SHIFT</b> Gallop <b>X</b> Brake <b>SPACE</b> Strike <b>Q</b> Backhand <b>R</b> Reset ball <b>ESC</b> Pause</footer>{s.paused&&<div className="pause">PAUSED<br/><button onClick={s.togglePause}>RESUME</button></div>}</div>}
export function Game(){const setSec=useMatch(s=>s.setSeconds),paused=useMatch(s=>s.paused),toggle=useMatch(s=>s.togglePause),reset=useMatch(s=>s.resetBall);useEffect(()=>{const t=setInterval(()=>{if(!paused)setSec(Math.max(0,useMatch.getState().seconds-1))},1000);const p=()=>toggle(),r=()=>reset();window.addEventListener("polo-pause",p);window.addEventListener("polo-reset",r);return()=>{clearInterval(t);window.removeEventListener("polo-pause",p);window.removeEventListener("polo-reset",r)}},[paused,setSec,toggle,reset]);return <main><Canvas shadows camera={{fov:54,position:[0,8,25]}}><Scene/></Canvas><Hud/></main>}
